FROM golang:1.23

WORKDIR /app

COPY lead-service/go.* /app/

RUN go mod download

COPY config/conf.yaml /app/config/conf.yaml

COPY lead-service/. /app/

WORKDIR /app/cmd

RUN go build -o /app/main .

CMD ["/app/main"]
