FROM golang:1.23

WORKDIR /app

COPY lead-service/go.* .

RUN go mod download

COPY config/conf.yaml ./config/conf.yaml

COPY lead-service/. .

WORKDIR /app/cmd

RUN go build -o /app/main .

CMD ["/app/main"]