FROM golang:1.23

WORKDIR /app

COPY api-gateway/go.* /app/

RUN go mod download

COPY config/conf.yaml /app/config/conf.yaml

COPY api-gateway/. /app/

WORKDIR /app/cmd

RUN go build -o /app/main .

CMD ["/app/main"]
