FROM golang:1.23

WORKDIR /app

COPY item-service/go.* .

RUN go mod download

COPY config/conf.yaml /app/config/conf.yaml

COPY item-service/. .

WORKDIR /app/cmd

RUN go build -o /app/main .
CMD ["/app/main"]