version: "3"

tasks:
  default:
    cmds:
      - task: run

  run:
    desc: Run the docker compose up
    cmds:
      - docker compose up


  build:
    desc: Build the docker container
    cmds:
      - docker compose build
  
  stop:
    desc: Stop the docker container
    cmds:
      - docker compose down

  restart:
    desc: Restart the docker container
    cmds:
      - task stop
      - task run

  logs:
    desc: Show logs
    cmds:
      - docker compose logs -f --tail=50

  logs-service:
    desc: Show logs for certain service
    cmds:
      - docker compose logs -f {{.CLI_ARGS}}

  proto-item:
    desc: "Compilation of item-service and gateway"
    cmds:
      - protoc -I . -I ./third-party -I ./third-party/googleapis --go_out=./item-service/ --go-grpc_out=./item-service/ ./proto/structures.proto
      - protoc -I . -I ./proto/item-grpc -I ./third-party -I ./third-party/googleapis --go_out=./item-service --go-grpc_out=./item-service --validate_out="lang=go:./item-service" ./proto/item-grpc/item.proto
      - protoc -I. -I ./proto/item-grpc -I ./third-party -I ./third-party/googleapis --go_out=./api-gateway/ --go-grpc_out=./api-gateway/ ./proto/structures.proto
      - protoc -I. -I ./proto/item-grpc -I ./third-party -I ./third-party/googleapis -I ./api-gateway --go_out=./api-gateway --grpc-gateway_out=./api-gateway --go-grpc_out=./api-gateway --validate_out="lang=go:./api-gateway" ./proto/item-grpc/gateway.proto

  proto-lead:
    desc: "Compilation of lead-service and gateway"
    cmds:
      - protoc -I . -I ./third-party -I ./third-party/googleapis --go_out=./lead-service/ --go-grpc_out=./lead-service/ ./proto/structures.proto
      - protoc -I . -I ./proto/lead-grpc -I ./third-party -I ./third-party/googleapis -I ./lead-service --go_out=./lead-service --go-grpc_out=./lead-service --validate_out="lang=go:./lead-service" ./proto/lead-grpc/lead-product.proto
      - protoc -I . -I ./proto/lead-grpc -I ./third-party -I ./third-party/googleapis -I ./lead-service --go_out=./lead-service --go-grpc_out=./lead-service --validate_out="lang=go:./lead-service" ./proto/lead-grpc/lead.proto
      - protoc -I . -I ./proto/lead-grpc -I ./third-party -I ./third-party/googleapis --go_out=./api-gateway/ --go-grpc_out=./api-gateway/ ./proto/structures.proto
      - protoc -I . -I ./proto/lead-grpc -I ./third-party -I ./third-party/googleapis -I ./api-gateway --go_out=./api-gateway --go-grpc_out=./api-gateway --grpc-gateway_out=./api-gateway  --validate_out="lang=go:./api-gateway" ./proto/lead-grpc/g-lead-product.proto
      - protoc -I . -I ./proto/lead-grpc -I ./third-party -I ./third-party/googleapis -I ./api-gateway --go_out=./api-gateway --go-grpc_out=./api-gateway --grpc-gateway_out=./api-gateway  --validate_out="lang=go:./api-gateway" ./proto/lead-grpc/gateway.proto
      - protoc -I . -I proto/item-grpc -I ./third-party -I ./third-party/googleapis --go_out=./lead-service --go-grpc_out=./lead-service ./proto/item-grpc/lead.proto

  proto-structures:
    desc: "Compile structures.proto for all services"
    cmds:
      - protoc -I . -I ./third-party -I ./third-party/googleapis --go_out=./api-gateway/ --go-grpc_out=./api-gateway/ ./proto/structures.proto
      - protoc -I . -I ./third-party -I ./third-party/googleapis --go_out=./item-service/ --go-grpc_out=./item-service/ ./proto/structures.proto
      - protoc -I . -I ./third-party -I ./third-party/googleapis --go_out=./lead-service/ --go-grpc_out=./lead-service/ ./proto/structures.proto

  proto-all:
    desc: "Compile all .proto for all services"
    cmds:
    - task: proto-item
    - task: proto-lead
    - task: proto-structures

