// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: lead-service/grpc/models/structures.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lead struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email            string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone            string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Company          string                 `protobuf:"bytes,4,opt,name=company,proto3" json:"company,omitempty"`
	Products         []*Product             `protobuf:"bytes,5,rep,name=products,proto3" json:"products,omitempty"`
	Visits           uint32                 `protobuf:"varint,6,opt,name=visits,proto3" json:"visits,omitempty"`
	LastVisit        string                 `protobuf:"bytes,7,opt,name=lastVisit,proto3" json:"lastVisit,omitempty"`
	TotalSales       float64                `protobuf:"fixed64,8,opt,name=totalSales,proto3" json:"totalSales,omitempty"`
	LastPurchaseDays uint32                 `protobuf:"varint,9,opt,name=lastPurchaseDays,proto3" json:"lastPurchaseDays,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Lead) Reset() {
	*x = Lead{}
	mi := &file_lead_service_grpc_models_structures_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lead) ProtoMessage() {}

func (x *Lead) ProtoReflect() protoreflect.Message {
	mi := &file_lead_service_grpc_models_structures_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lead.ProtoReflect.Descriptor instead.
func (*Lead) Descriptor() ([]byte, []int) {
	return file_lead_service_grpc_models_structures_proto_rawDescGZIP(), []int{0}
}

func (x *Lead) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Lead) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Lead) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Lead) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *Lead) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *Lead) GetVisits() uint32 {
	if x != nil {
		return x.Visits
	}
	return 0
}

func (x *Lead) GetLastVisit() string {
	if x != nil {
		return x.LastVisit
	}
	return ""
}

func (x *Lead) GetTotalSales() float64 {
	if x != nil {
		return x.TotalSales
	}
	return 0
}

func (x *Lead) GetLastPurchaseDays() uint32 {
	if x != nil {
		return x.LastPurchaseDays
	}
	return 0
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	InStock       uint32                 `protobuf:"varint,6,opt,name=inStock,proto3" json:"inStock,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	LeadID        uint32                 `protobuf:"varint,8,opt,name=leadID,proto3" json:"leadID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_lead_service_grpc_models_structures_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_lead_service_grpc_models_structures_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_lead_service_grpc_models_structures_proto_rawDescGZIP(), []int{1}
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Product) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Product) GetInStock() uint32 {
	if x != nil {
		return x.InStock
	}
	return 0
}

func (x *Product) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Product) GetLeadID() uint32 {
	if x != nil {
		return x.LeadID
	}
	return 0
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	InStock       uint32                 `protobuf:"varint,6,opt,name=inStock,proto3" json:"inStock,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_lead_service_grpc_models_structures_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_lead_service_grpc_models_structures_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_lead_service_grpc_models_structures_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Item) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Item) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Item) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Item) GetInStock() uint32 {
	if x != nil {
		return x.InStock
	}
	return 0
}

func (x *Item) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_lead_service_grpc_models_structures_proto protoreflect.FileDescriptor

const file_lead_service_grpc_models_structures_proto_rawDesc = "" +
	"\n" +
	")lead-service/grpc/models/structures.proto\x12\x06models\"\x8f\x02\n" +
	"\x04Lead\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x18\n" +
	"\acompany\x18\x04 \x01(\tR\acompany\x12+\n" +
	"\bproducts\x18\x05 \x03(\v2\x0f.models.ProductR\bproducts\x12\x16\n" +
	"\x06visits\x18\x06 \x01(\rR\x06visits\x12\x1c\n" +
	"\tlastVisit\x18\a \x01(\tR\tlastVisit\x12\x1e\n" +
	"\n" +
	"totalSales\x18\b \x01(\x01R\n" +
	"totalSales\x12*\n" +
	"\x10lastPurchaseDays\x18\t \x01(\rR\x10lastPurchaseDays\"\xd7\x01\n" +
	"\aProduct\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x18\n" +
	"\ainStock\x18\x06 \x01(\rR\ainStock\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x16\n" +
	"\x06leadID\x18\b \x01(\rR\x06leadID\"\xbc\x01\n" +
	"\x04Item\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x18\n" +
	"\ainStock\x18\x06 \x01(\rR\ainStock\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06statusB\x15Z\x13grpc/models; modelsb\x06proto3"

var (
	file_lead_service_grpc_models_structures_proto_rawDescOnce sync.Once
	file_lead_service_grpc_models_structures_proto_rawDescData []byte
)

func file_lead_service_grpc_models_structures_proto_rawDescGZIP() []byte {
	file_lead_service_grpc_models_structures_proto_rawDescOnce.Do(func() {
		file_lead_service_grpc_models_structures_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lead_service_grpc_models_structures_proto_rawDesc), len(file_lead_service_grpc_models_structures_proto_rawDesc)))
	})
	return file_lead_service_grpc_models_structures_proto_rawDescData
}

var file_lead_service_grpc_models_structures_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_lead_service_grpc_models_structures_proto_goTypes = []any{
	(*Lead)(nil),    // 0: models.Lead
	(*Product)(nil), // 1: models.Product
	(*Item)(nil),    // 2: models.Item
}
var file_lead_service_grpc_models_structures_proto_depIdxs = []int32{
	1, // 0: models.Lead.products:type_name -> models.Product
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lead_service_grpc_models_structures_proto_init() }
func file_lead_service_grpc_models_structures_proto_init() {
	if File_lead_service_grpc_models_structures_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lead_service_grpc_models_structures_proto_rawDesc), len(file_lead_service_grpc_models_structures_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lead_service_grpc_models_structures_proto_goTypes,
		DependencyIndexes: file_lead_service_grpc_models_structures_proto_depIdxs,
		MessageInfos:      file_lead_service_grpc_models_structures_proto_msgTypes,
	}.Build()
	File_lead_service_grpc_models_structures_proto = out.File
	file_lead_service_grpc_models_structures_proto_goTypes = nil
	file_lead_service_grpc_models_structures_proto_depIdxs = nil
}
