// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: proto/structures.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LeadResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email            string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone            string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Company          string                 `protobuf:"bytes,5,opt,name=company,proto3" json:"company,omitempty"`
	Products         []*ItemResponse        `protobuf:"bytes,6,rep,name=products,proto3" json:"products,omitempty"`
	Visits           uint32                 `protobuf:"varint,7,opt,name=visits,proto3" json:"visits,omitempty"`
	LastVisit        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=lastVisit,proto3" json:"lastVisit,omitempty"`
	TotalSales       float64                `protobuf:"fixed64,9,opt,name=totalSales,proto3" json:"totalSales,omitempty"`
	LastPurchaseDays uint32                 `protobuf:"varint,10,opt,name=lastPurchaseDays,proto3" json:"lastPurchaseDays,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LeadResponse) Reset() {
	*x = LeadResponse{}
	mi := &file_proto_structures_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeadResponse) ProtoMessage() {}

func (x *LeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_structures_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeadResponse.ProtoReflect.Descriptor instead.
func (*LeadResponse) Descriptor() ([]byte, []int) {
	return file_proto_structures_proto_rawDescGZIP(), []int{0}
}

func (x *LeadResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LeadResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LeadResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LeadResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LeadResponse) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *LeadResponse) GetProducts() []*ItemResponse {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *LeadResponse) GetVisits() uint32 {
	if x != nil {
		return x.Visits
	}
	return 0
}

func (x *LeadResponse) GetLastVisit() *timestamppb.Timestamp {
	if x != nil {
		return x.LastVisit
	}
	return nil
}

func (x *LeadResponse) GetTotalSales() float64 {
	if x != nil {
		return x.TotalSales
	}
	return 0
}

func (x *LeadResponse) GetLastPurchaseDays() uint32 {
	if x != nil {
		return x.LastPurchaseDays
	}
	return 0
}

type LeadRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email            string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone            string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Company          string                 `protobuf:"bytes,4,opt,name=company,proto3" json:"company,omitempty"`
	Products         []*ItemResponse        `protobuf:"bytes,5,rep,name=products,proto3" json:"products,omitempty"`
	Visits           uint32                 `protobuf:"varint,6,opt,name=visits,proto3" json:"visits,omitempty"`
	LastVisit        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=lastVisit,proto3" json:"lastVisit,omitempty"`
	TotalSales       float64                `protobuf:"fixed64,8,opt,name=totalSales,proto3" json:"totalSales,omitempty"`
	LastPurchaseDays uint32                 `protobuf:"varint,9,opt,name=lastPurchaseDays,proto3" json:"lastPurchaseDays,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LeadRequest) Reset() {
	*x = LeadRequest{}
	mi := &file_proto_structures_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeadRequest) ProtoMessage() {}

func (x *LeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_structures_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeadRequest.ProtoReflect.Descriptor instead.
func (*LeadRequest) Descriptor() ([]byte, []int) {
	return file_proto_structures_proto_rawDescGZIP(), []int{1}
}

func (x *LeadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LeadRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LeadRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LeadRequest) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *LeadRequest) GetProducts() []*ItemResponse {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *LeadRequest) GetVisits() uint32 {
	if x != nil {
		return x.Visits
	}
	return 0
}

func (x *LeadRequest) GetLastVisit() *timestamppb.Timestamp {
	if x != nil {
		return x.LastVisit
	}
	return nil
}

func (x *LeadRequest) GetTotalSales() float64 {
	if x != nil {
		return x.TotalSales
	}
	return 0
}

func (x *LeadRequest) GetLastPurchaseDays() uint32 {
	if x != nil {
		return x.LastPurchaseDays
	}
	return 0
}

type ItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	InStock       uint32                 `protobuf:"varint,7,opt,name=inStock,proto3" json:"inStock,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemResponse) Reset() {
	*x = ItemResponse{}
	mi := &file_proto_structures_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemResponse) ProtoMessage() {}

func (x *ItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_structures_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemResponse.ProtoReflect.Descriptor instead.
func (*ItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_structures_proto_rawDescGZIP(), []int{2}
}

func (x *ItemResponse) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ItemResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ItemResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ItemResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ItemResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ItemResponse) GetInStock() uint32 {
	if x != nil {
		return x.InStock
	}
	return 0
}

func (x *ItemResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	InStock       uint32                 `protobuf:"varint,6,opt,name=inStock,proto3" json:"inStock,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemRequest) Reset() {
	*x = ItemRequest{}
	mi := &file_proto_structures_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRequest) ProtoMessage() {}

func (x *ItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_structures_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRequest.ProtoReflect.Descriptor instead.
func (*ItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_structures_proto_rawDescGZIP(), []int{3}
}

func (x *ItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ItemRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ItemRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ItemRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ItemRequest) GetInStock() uint32 {
	if x != nil {
		return x.InStock
	}
	return 0
}

func (x *ItemRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_structures_proto protoreflect.FileDescriptor

const file_proto_structures_proto_rawDesc = "" +
	"\n" +
	"\x16proto/structures.proto\x12\x06models\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc8\x02\n" +
	"\fLeadResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x18\n" +
	"\acompany\x18\x05 \x01(\tR\acompany\x120\n" +
	"\bproducts\x18\x06 \x03(\v2\x14.models.ItemResponseR\bproducts\x12\x16\n" +
	"\x06visits\x18\a \x01(\rR\x06visits\x128\n" +
	"\tlastVisit\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tlastVisit\x12\x1e\n" +
	"\n" +
	"totalSales\x18\t \x01(\x01R\n" +
	"totalSales\x12*\n" +
	"\x10lastPurchaseDays\x18\n" +
	" \x01(\rR\x10lastPurchaseDays\"\xb7\x02\n" +
	"\vLeadRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x18\n" +
	"\acompany\x18\x04 \x01(\tR\acompany\x120\n" +
	"\bproducts\x18\x05 \x03(\v2\x14.models.ItemResponseR\bproducts\x12\x16\n" +
	"\x06visits\x18\x06 \x01(\rR\x06visits\x128\n" +
	"\tlastVisit\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tlastVisit\x12\x1e\n" +
	"\n" +
	"totalSales\x18\b \x01(\x01R\n" +
	"totalSales\x12*\n" +
	"\x10lastPurchaseDays\x18\t \x01(\rR\x10lastPurchaseDays\"\xe3\x01\n" +
	"\fItemResponse\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x18\n" +
	"\ainStock\x18\a \x01(\rR\ainStock\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\"\xc3\x01\n" +
	"\vItemRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x18\n" +
	"\ainStock\x18\x06 \x01(\rR\ainStock\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06statusB\x15Z\x13grpc/models; modelsb\x06proto3"

var (
	file_proto_structures_proto_rawDescOnce sync.Once
	file_proto_structures_proto_rawDescData []byte
)

func file_proto_structures_proto_rawDescGZIP() []byte {
	file_proto_structures_proto_rawDescOnce.Do(func() {
		file_proto_structures_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_structures_proto_rawDesc), len(file_proto_structures_proto_rawDesc)))
	})
	return file_proto_structures_proto_rawDescData
}

var file_proto_structures_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_structures_proto_goTypes = []any{
	(*LeadResponse)(nil),          // 0: models.LeadResponse
	(*LeadRequest)(nil),           // 1: models.LeadRequest
	(*ItemResponse)(nil),          // 2: models.ItemResponse
	(*ItemRequest)(nil),           // 3: models.ItemRequest
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_proto_structures_proto_depIdxs = []int32{
	2, // 0: models.LeadResponse.products:type_name -> models.ItemResponse
	4, // 1: models.LeadResponse.lastVisit:type_name -> google.protobuf.Timestamp
	2, // 2: models.LeadRequest.products:type_name -> models.ItemResponse
	4, // 3: models.LeadRequest.lastVisit:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_structures_proto_init() }
func file_proto_structures_proto_init() {
	if File_proto_structures_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_structures_proto_rawDesc), len(file_proto_structures_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_structures_proto_goTypes,
		DependencyIndexes: file_proto_structures_proto_depIdxs,
		MessageInfos:      file_proto_structures_proto_msgTypes,
	}.Build()
	File_proto_structures_proto = out.File
	file_proto_structures_proto_goTypes = nil
	file_proto_structures_proto_depIdxs = nil
}
