// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: lead-service/grpc/lead-grpc/lead-product.proto

package proto

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddProductsToLeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductIds    []uint32               `protobuf:"varint,2,rep,packed,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductsToLeadRequest) Reset() {
	*x = AddProductsToLeadRequest{}
	mi := &file_lead_service_grpc_lead_grpc_lead_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductsToLeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductsToLeadRequest) ProtoMessage() {}

func (x *AddProductsToLeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_service_grpc_lead_grpc_lead_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductsToLeadRequest.ProtoReflect.Descriptor instead.
func (*AddProductsToLeadRequest) Descriptor() ([]byte, []int) {
	return file_lead_service_grpc_lead_grpc_lead_product_proto_rawDescGZIP(), []int{0}
}

func (x *AddProductsToLeadRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddProductsToLeadRequest) GetProductIds() []uint32 {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

type AddProductsToLeadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductsToLeadResponse) Reset() {
	*x = AddProductsToLeadResponse{}
	mi := &file_lead_service_grpc_lead_grpc_lead_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductsToLeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductsToLeadResponse) ProtoMessage() {}

func (x *AddProductsToLeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lead_service_grpc_lead_grpc_lead_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductsToLeadResponse.ProtoReflect.Descriptor instead.
func (*AddProductsToLeadResponse) Descriptor() ([]byte, []int) {
	return file_lead_service_grpc_lead_grpc_lead_product_proto_rawDescGZIP(), []int{1}
}

func (x *AddProductsToLeadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteLeadProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     uint32                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLeadProductRequest) Reset() {
	*x = DeleteLeadProductRequest{}
	mi := &file_lead_service_grpc_lead_grpc_lead_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLeadProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLeadProductRequest) ProtoMessage() {}

func (x *DeleteLeadProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_service_grpc_lead_grpc_lead_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLeadProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteLeadProductRequest) Descriptor() ([]byte, []int) {
	return file_lead_service_grpc_lead_grpc_lead_product_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteLeadProductRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteLeadProductRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type DeleteLeadProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLeadProductResponse) Reset() {
	*x = DeleteLeadProductResponse{}
	mi := &file_lead_service_grpc_lead_grpc_lead_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLeadProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLeadProductResponse) ProtoMessage() {}

func (x *DeleteLeadProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lead_service_grpc_lead_grpc_lead_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLeadProductResponse.ProtoReflect.Descriptor instead.
func (*DeleteLeadProductResponse) Descriptor() ([]byte, []int) {
	return file_lead_service_grpc_lead_grpc_lead_product_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteLeadProductResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteLeadProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLeadProductsRequest) Reset() {
	*x = DeleteLeadProductsRequest{}
	mi := &file_lead_service_grpc_lead_grpc_lead_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLeadProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLeadProductsRequest) ProtoMessage() {}

func (x *DeleteLeadProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_service_grpc_lead_grpc_lead_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLeadProductsRequest.ProtoReflect.Descriptor instead.
func (*DeleteLeadProductsRequest) Descriptor() ([]byte, []int) {
	return file_lead_service_grpc_lead_grpc_lead_product_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteLeadProductsRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteLeadProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLeadProductsResponse) Reset() {
	*x = DeleteLeadProductsResponse{}
	mi := &file_lead_service_grpc_lead_grpc_lead_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLeadProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLeadProductsResponse) ProtoMessage() {}

func (x *DeleteLeadProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lead_service_grpc_lead_grpc_lead_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLeadProductsResponse.ProtoReflect.Descriptor instead.
func (*DeleteLeadProductsResponse) Descriptor() ([]byte, []int) {
	return file_lead_service_grpc_lead_grpc_lead_product_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteLeadProductsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_lead_service_grpc_lead_grpc_lead_product_proto protoreflect.FileDescriptor

const file_lead_service_grpc_lead_grpc_lead_product_proto_rawDesc = "" +
	"\n" +
	".lead-service/grpc/lead-grpc/lead-product.proto\x12\x05proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"T\n" +
	"\x18AddProductsToLeadRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\rB\a\xfaB\x04*\x02 \x00R\x02id\x12\x1f\n" +
	"\vproduct_ids\x18\x02 \x03(\rR\n" +
	"productIds\"5\n" +
	"\x19AddProductsToLeadResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"R\n" +
	"\x18DeleteLeadProductRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\rB\a\xfaB\x04*\x02 \x00R\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\rR\tproductId\"5\n" +
	"\x19DeleteLeadProductResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"4\n" +
	"\x19DeleteLeadProductsRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\rB\a\xfaB\x04*\x02 \x00R\x02id\"6\n" +
	"\x1aDeleteLeadProductsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xf4\x02\n" +
	"\x12LeadProductService\x12p\n" +
	"\x11AddProductsToLead\x12\x1f.proto.AddProductsToLeadRequest\x1a .proto.AddProductsToLeadResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/lead-product\x12u\n" +
	"\x12DeleteLeadProducts\x12 .proto.DeleteLeadProductsRequest\x1a!.proto.DeleteLeadProductsResponse\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/lead-product/{id}\x12u\n" +
	"\x11DeleteLeadProduct\x12\x1f.proto.DeleteLeadProductRequest\x1a .proto.DeleteLeadProductResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/lead-product/{id}B\x16Z\x14grpc/lead-grpc;protob\x06proto3"

var (
	file_lead_service_grpc_lead_grpc_lead_product_proto_rawDescOnce sync.Once
	file_lead_service_grpc_lead_grpc_lead_product_proto_rawDescData []byte
)

func file_lead_service_grpc_lead_grpc_lead_product_proto_rawDescGZIP() []byte {
	file_lead_service_grpc_lead_grpc_lead_product_proto_rawDescOnce.Do(func() {
		file_lead_service_grpc_lead_grpc_lead_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lead_service_grpc_lead_grpc_lead_product_proto_rawDesc), len(file_lead_service_grpc_lead_grpc_lead_product_proto_rawDesc)))
	})
	return file_lead_service_grpc_lead_grpc_lead_product_proto_rawDescData
}

var file_lead_service_grpc_lead_grpc_lead_product_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_lead_service_grpc_lead_grpc_lead_product_proto_goTypes = []any{
	(*AddProductsToLeadRequest)(nil),   // 0: proto.AddProductsToLeadRequest
	(*AddProductsToLeadResponse)(nil),  // 1: proto.AddProductsToLeadResponse
	(*DeleteLeadProductRequest)(nil),   // 2: proto.DeleteLeadProductRequest
	(*DeleteLeadProductResponse)(nil),  // 3: proto.DeleteLeadProductResponse
	(*DeleteLeadProductsRequest)(nil),  // 4: proto.DeleteLeadProductsRequest
	(*DeleteLeadProductsResponse)(nil), // 5: proto.DeleteLeadProductsResponse
}
var file_lead_service_grpc_lead_grpc_lead_product_proto_depIdxs = []int32{
	0, // 0: proto.LeadProductService.AddProductsToLead:input_type -> proto.AddProductsToLeadRequest
	4, // 1: proto.LeadProductService.DeleteLeadProducts:input_type -> proto.DeleteLeadProductsRequest
	2, // 2: proto.LeadProductService.DeleteLeadProduct:input_type -> proto.DeleteLeadProductRequest
	1, // 3: proto.LeadProductService.AddProductsToLead:output_type -> proto.AddProductsToLeadResponse
	5, // 4: proto.LeadProductService.DeleteLeadProducts:output_type -> proto.DeleteLeadProductsResponse
	3, // 5: proto.LeadProductService.DeleteLeadProduct:output_type -> proto.DeleteLeadProductResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lead_service_grpc_lead_grpc_lead_product_proto_init() }
func file_lead_service_grpc_lead_grpc_lead_product_proto_init() {
	if File_lead_service_grpc_lead_grpc_lead_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lead_service_grpc_lead_grpc_lead_product_proto_rawDesc), len(file_lead_service_grpc_lead_grpc_lead_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lead_service_grpc_lead_grpc_lead_product_proto_goTypes,
		DependencyIndexes: file_lead_service_grpc_lead_grpc_lead_product_proto_depIdxs,
		MessageInfos:      file_lead_service_grpc_lead_grpc_lead_product_proto_msgTypes,
	}.Build()
	File_lead_service_grpc_lead_grpc_lead_product_proto = out.File
	file_lead_service_grpc_lead_grpc_lead_product_proto_goTypes = nil
	file_lead_service_grpc_lead_grpc_lead_product_proto_depIdxs = nil
}
