// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: lead-service/grpc/lead-grpc/lead.proto

package proto

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	models "github.com/fiveret/crm-golang/grpc/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeadRequest) Reset() {
	*x = GetLeadRequest{}
	mi := &file_lead_service_grpc_lead_grpc_lead_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeadRequest) ProtoMessage() {}

func (x *GetLeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_service_grpc_lead_grpc_lead_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeadRequest.ProtoReflect.Descriptor instead.
func (*GetLeadRequest) Descriptor() ([]byte, []int) {
	return file_lead_service_grpc_lead_grpc_lead_proto_rawDescGZIP(), []int{0}
}

func (x *GetLeadRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetLeadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Lead          *models.Lead           `protobuf:"bytes,2,opt,name=lead,proto3" json:"lead,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeadResponse) Reset() {
	*x = GetLeadResponse{}
	mi := &file_lead_service_grpc_lead_grpc_lead_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeadResponse) ProtoMessage() {}

func (x *GetLeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lead_service_grpc_lead_grpc_lead_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeadResponse.ProtoReflect.Descriptor instead.
func (*GetLeadResponse) Descriptor() ([]byte, []int) {
	return file_lead_service_grpc_lead_grpc_lead_proto_rawDescGZIP(), []int{1}
}

func (x *GetLeadResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetLeadResponse) GetLead() *models.Lead {
	if x != nil {
		return x.Lead
	}
	return nil
}

func (x *GetLeadResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetLeadResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetLeadsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeadsRequest) Reset() {
	*x = GetLeadsRequest{}
	mi := &file_lead_service_grpc_lead_grpc_lead_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeadsRequest) ProtoMessage() {}

func (x *GetLeadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_service_grpc_lead_grpc_lead_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeadsRequest.ProtoReflect.Descriptor instead.
func (*GetLeadsRequest) Descriptor() ([]byte, []int) {
	return file_lead_service_grpc_lead_grpc_lead_proto_rawDescGZIP(), []int{2}
}

func (x *GetLeadsRequest) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

type GetLeadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leads         []*models.Lead         `protobuf:"bytes,1,rep,name=leads,proto3" json:"leads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeadsResponse) Reset() {
	*x = GetLeadsResponse{}
	mi := &file_lead_service_grpc_lead_grpc_lead_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeadsResponse) ProtoMessage() {}

func (x *GetLeadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lead_service_grpc_lead_grpc_lead_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeadsResponse.ProtoReflect.Descriptor instead.
func (*GetLeadsResponse) Descriptor() ([]byte, []int) {
	return file_lead_service_grpc_lead_grpc_lead_proto_rawDescGZIP(), []int{3}
}

func (x *GetLeadsResponse) GetLeads() []*models.Lead {
	if x != nil {
		return x.Leads
	}
	return nil
}

type NewLeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lead          *models.Lead           `protobuf:"bytes,1,opt,name=lead,proto3" json:"lead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewLeadRequest) Reset() {
	*x = NewLeadRequest{}
	mi := &file_lead_service_grpc_lead_grpc_lead_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewLeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewLeadRequest) ProtoMessage() {}

func (x *NewLeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_service_grpc_lead_grpc_lead_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewLeadRequest.ProtoReflect.Descriptor instead.
func (*NewLeadRequest) Descriptor() ([]byte, []int) {
	return file_lead_service_grpc_lead_grpc_lead_proto_rawDescGZIP(), []int{4}
}

func (x *NewLeadRequest) GetLead() *models.Lead {
	if x != nil {
		return x.Lead
	}
	return nil
}

type NewLeadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lead          *models.Lead           `protobuf:"bytes,1,opt,name=lead,proto3" json:"lead,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewLeadResponse) Reset() {
	*x = NewLeadResponse{}
	mi := &file_lead_service_grpc_lead_grpc_lead_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewLeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewLeadResponse) ProtoMessage() {}

func (x *NewLeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lead_service_grpc_lead_grpc_lead_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewLeadResponse.ProtoReflect.Descriptor instead.
func (*NewLeadResponse) Descriptor() ([]byte, []int) {
	return file_lead_service_grpc_lead_grpc_lead_proto_rawDescGZIP(), []int{5}
}

func (x *NewLeadResponse) GetLead() *models.Lead {
	if x != nil {
		return x.Lead
	}
	return nil
}

func (x *NewLeadResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type PutLeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Lead          *models.Lead           `protobuf:"bytes,2,opt,name=lead,proto3" json:"lead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutLeadRequest) Reset() {
	*x = PutLeadRequest{}
	mi := &file_lead_service_grpc_lead_grpc_lead_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutLeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutLeadRequest) ProtoMessage() {}

func (x *PutLeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_service_grpc_lead_grpc_lead_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutLeadRequest.ProtoReflect.Descriptor instead.
func (*PutLeadRequest) Descriptor() ([]byte, []int) {
	return file_lead_service_grpc_lead_grpc_lead_proto_rawDescGZIP(), []int{6}
}

func (x *PutLeadRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PutLeadRequest) GetLead() *models.Lead {
	if x != nil {
		return x.Lead
	}
	return nil
}

type PutLeadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lead          *models.Lead           `protobuf:"bytes,1,opt,name=lead,proto3" json:"lead,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutLeadResponse) Reset() {
	*x = PutLeadResponse{}
	mi := &file_lead_service_grpc_lead_grpc_lead_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutLeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutLeadResponse) ProtoMessage() {}

func (x *PutLeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lead_service_grpc_lead_grpc_lead_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutLeadResponse.ProtoReflect.Descriptor instead.
func (*PutLeadResponse) Descriptor() ([]byte, []int) {
	return file_lead_service_grpc_lead_grpc_lead_proto_rawDescGZIP(), []int{7}
}

func (x *PutLeadResponse) GetLead() *models.Lead {
	if x != nil {
		return x.Lead
	}
	return nil
}

func (x *PutLeadResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PutLeadResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DeleteLeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLeadRequest) Reset() {
	*x = DeleteLeadRequest{}
	mi := &file_lead_service_grpc_lead_grpc_lead_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLeadRequest) ProtoMessage() {}

func (x *DeleteLeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lead_service_grpc_lead_grpc_lead_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLeadRequest.ProtoReflect.Descriptor instead.
func (*DeleteLeadRequest) Descriptor() ([]byte, []int) {
	return file_lead_service_grpc_lead_grpc_lead_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteLeadRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteLeadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLeadResponse) Reset() {
	*x = DeleteLeadResponse{}
	mi := &file_lead_service_grpc_lead_grpc_lead_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLeadResponse) ProtoMessage() {}

func (x *DeleteLeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lead_service_grpc_lead_grpc_lead_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLeadResponse.ProtoReflect.Descriptor instead.
func (*DeleteLeadResponse) Descriptor() ([]byte, []int) {
	return file_lead_service_grpc_lead_grpc_lead_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteLeadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_lead_service_grpc_lead_grpc_lead_proto protoreflect.FileDescriptor

const file_lead_service_grpc_lead_grpc_lead_proto_rawDesc = "" +
	"\n" +
	"&lead-service/grpc/lead-grpc/lead.proto\x12\x05proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgrpc/models/structures.proto\")\n" +
	"\x0eGetLeadRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\rB\a\xfaB\x04*\x02 \x00R\x02id\"\xb7\x01\n" +
	"\x0fGetLeadResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12 \n" +
	"\x04lead\x18\x02 \x01(\v2\f.models.LeadR\x04lead\x128\n" +
	"\tcreatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"?\n" +
	"\x0fGetLeadsRequest\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\"6\n" +
	"\x10GetLeadsResponse\x12\"\n" +
	"\x05leads\x18\x01 \x03(\v2\f.models.LeadR\x05leads\"2\n" +
	"\x0eNewLeadRequest\x12 \n" +
	"\x04lead\x18\x01 \x01(\v2\f.models.LeadR\x04lead\"m\n" +
	"\x0fNewLeadResponse\x12 \n" +
	"\x04lead\x18\x01 \x01(\v2\f.models.LeadR\x04lead\x128\n" +
	"\tcreatedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"K\n" +
	"\x0ePutLeadRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\rB\a\xfaB\x04*\x02 \x00R\x02id\x12 \n" +
	"\x04lead\x18\x02 \x01(\v2\f.models.LeadR\x04lead\"\xa7\x01\n" +
	"\x0fPutLeadResponse\x12 \n" +
	"\x04lead\x18\x01 \x01(\v2\f.models.LeadR\x04lead\x128\n" +
	"\tcreatedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\",\n" +
	"\x11DeleteLeadRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\rB\a\xfaB\x04*\x02 \x00R\x02id\".\n" +
	"\x12DeleteLeadResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xb0\x03\n" +
	"\vLeadService\x12O\n" +
	"\aGetLead\x12\x15.proto.GetLeadRequest\x1a\x16.proto.GetLeadResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/lead/{id}\x12M\n" +
	"\bGetLeads\x12\x16.proto.GetLeadsRequest\x1a\x17.proto.GetLeadsResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/lead\x12X\n" +
	"\n" +
	"DeleteLead\x12\x18.proto.DeleteLeadRequest\x1a\x19.proto.DeleteLeadResponse\"\x15\x82\xd3\xe4\x93\x02\x0f*\r/v1/lead/{id}\x12P\n" +
	"\aNewLead\x12\x15.proto.NewLeadRequest\x1a\x16.proto.NewLeadResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x04lead\"\b/v1/lead\x12U\n" +
	"\aPutLead\x12\x15.proto.PutLeadRequest\x1a\x16.proto.PutLeadResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x04lead\x1a\r/v1/lead/{id}B\x16Z\x14grpc/lead-grpc;protob\x06proto3"

var (
	file_lead_service_grpc_lead_grpc_lead_proto_rawDescOnce sync.Once
	file_lead_service_grpc_lead_grpc_lead_proto_rawDescData []byte
)

func file_lead_service_grpc_lead_grpc_lead_proto_rawDescGZIP() []byte {
	file_lead_service_grpc_lead_grpc_lead_proto_rawDescOnce.Do(func() {
		file_lead_service_grpc_lead_grpc_lead_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lead_service_grpc_lead_grpc_lead_proto_rawDesc), len(file_lead_service_grpc_lead_grpc_lead_proto_rawDesc)))
	})
	return file_lead_service_grpc_lead_grpc_lead_proto_rawDescData
}

var file_lead_service_grpc_lead_grpc_lead_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_lead_service_grpc_lead_grpc_lead_proto_goTypes = []any{
	(*GetLeadRequest)(nil),        // 0: proto.GetLeadRequest
	(*GetLeadResponse)(nil),       // 1: proto.GetLeadResponse
	(*GetLeadsRequest)(nil),       // 2: proto.GetLeadsRequest
	(*GetLeadsResponse)(nil),      // 3: proto.GetLeadsResponse
	(*NewLeadRequest)(nil),        // 4: proto.NewLeadRequest
	(*NewLeadResponse)(nil),       // 5: proto.NewLeadResponse
	(*PutLeadRequest)(nil),        // 6: proto.PutLeadRequest
	(*PutLeadResponse)(nil),       // 7: proto.PutLeadResponse
	(*DeleteLeadRequest)(nil),     // 8: proto.DeleteLeadRequest
	(*DeleteLeadResponse)(nil),    // 9: proto.DeleteLeadResponse
	(*models.Lead)(nil),           // 10: models.Lead
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 12: google.protobuf.Empty
}
var file_lead_service_grpc_lead_grpc_lead_proto_depIdxs = []int32{
	10, // 0: proto.GetLeadResponse.lead:type_name -> models.Lead
	11, // 1: proto.GetLeadResponse.createdAt:type_name -> google.protobuf.Timestamp
	11, // 2: proto.GetLeadResponse.updatedAt:type_name -> google.protobuf.Timestamp
	12, // 3: proto.GetLeadsRequest.empty:type_name -> google.protobuf.Empty
	10, // 4: proto.GetLeadsResponse.leads:type_name -> models.Lead
	10, // 5: proto.NewLeadRequest.lead:type_name -> models.Lead
	10, // 6: proto.NewLeadResponse.lead:type_name -> models.Lead
	11, // 7: proto.NewLeadResponse.createdAt:type_name -> google.protobuf.Timestamp
	10, // 8: proto.PutLeadRequest.lead:type_name -> models.Lead
	10, // 9: proto.PutLeadResponse.lead:type_name -> models.Lead
	11, // 10: proto.PutLeadResponse.createdAt:type_name -> google.protobuf.Timestamp
	11, // 11: proto.PutLeadResponse.updatedAt:type_name -> google.protobuf.Timestamp
	0,  // 12: proto.LeadService.GetLead:input_type -> proto.GetLeadRequest
	2,  // 13: proto.LeadService.GetLeads:input_type -> proto.GetLeadsRequest
	8,  // 14: proto.LeadService.DeleteLead:input_type -> proto.DeleteLeadRequest
	4,  // 15: proto.LeadService.NewLead:input_type -> proto.NewLeadRequest
	6,  // 16: proto.LeadService.PutLead:input_type -> proto.PutLeadRequest
	1,  // 17: proto.LeadService.GetLead:output_type -> proto.GetLeadResponse
	3,  // 18: proto.LeadService.GetLeads:output_type -> proto.GetLeadsResponse
	9,  // 19: proto.LeadService.DeleteLead:output_type -> proto.DeleteLeadResponse
	5,  // 20: proto.LeadService.NewLead:output_type -> proto.NewLeadResponse
	7,  // 21: proto.LeadService.PutLead:output_type -> proto.PutLeadResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_lead_service_grpc_lead_grpc_lead_proto_init() }
func file_lead_service_grpc_lead_grpc_lead_proto_init() {
	if File_lead_service_grpc_lead_grpc_lead_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lead_service_grpc_lead_grpc_lead_proto_rawDesc), len(file_lead_service_grpc_lead_grpc_lead_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lead_service_grpc_lead_grpc_lead_proto_goTypes,
		DependencyIndexes: file_lead_service_grpc_lead_grpc_lead_proto_depIdxs,
		MessageInfos:      file_lead_service_grpc_lead_grpc_lead_proto_msgTypes,
	}.Build()
	File_lead_service_grpc_lead_grpc_lead_proto = out.File
	file_lead_service_grpc_lead_grpc_lead_proto_goTypes = nil
	file_lead_service_grpc_lead_grpc_lead_proto_depIdxs = nil
}
