// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: item-service/grpc/item-grpc/item.proto

package proto

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	models "github.com/fiveret/product-service/grpc/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *models.Item           `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemRequest) Reset() {
	*x = CreateItemRequest{}
	mi := &file_item_service_grpc_item_grpc_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemRequest) ProtoMessage() {}

func (x *CreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_service_grpc_item_grpc_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemRequest.ProtoReflect.Descriptor instead.
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return file_item_service_grpc_item_grpc_item_proto_rawDescGZIP(), []int{0}
}

func (x *CreateItemRequest) GetItem() *models.Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type CreateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemResponse) Reset() {
	*x = CreateItemResponse{}
	mi := &file_item_service_grpc_item_grpc_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemResponse) ProtoMessage() {}

func (x *CreateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_service_grpc_item_grpc_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemResponse.ProtoReflect.Descriptor instead.
func (*CreateItemResponse) Descriptor() ([]byte, []int) {
	return file_item_service_grpc_item_grpc_item_proto_rawDescGZIP(), []int{1}
}

func (x *CreateItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateItemResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_item_service_grpc_item_grpc_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_service_grpc_item_grpc_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_item_service_grpc_item_grpc_item_proto_rawDescGZIP(), []int{2}
}

func (x *GetItemRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *models.Item           `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemResponse) Reset() {
	*x = GetItemResponse{}
	mi := &file_item_service_grpc_item_grpc_item_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemResponse) ProtoMessage() {}

func (x *GetItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_service_grpc_item_grpc_item_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemResponse.ProtoReflect.Descriptor instead.
func (*GetItemResponse) Descriptor() ([]byte, []int) {
	return file_item_service_grpc_item_grpc_item_proto_rawDescGZIP(), []int{3}
}

func (x *GetItemResponse) GetItem() *models.Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type GetItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsRequest) Reset() {
	*x = GetItemsRequest{}
	mi := &file_item_service_grpc_item_grpc_item_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsRequest) ProtoMessage() {}

func (x *GetItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_service_grpc_item_grpc_item_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsRequest.ProtoReflect.Descriptor instead.
func (*GetItemsRequest) Descriptor() ([]byte, []int) {
	return file_item_service_grpc_item_grpc_item_proto_rawDescGZIP(), []int{4}
}

func (x *GetItemsRequest) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

type GetItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*models.Item         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsResponse) Reset() {
	*x = GetItemsResponse{}
	mi := &file_item_service_grpc_item_grpc_item_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsResponse) ProtoMessage() {}

func (x *GetItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_service_grpc_item_grpc_item_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsResponse.ProtoReflect.Descriptor instead.
func (*GetItemsResponse) Descriptor() ([]byte, []int) {
	return file_item_service_grpc_item_grpc_item_proto_rawDescGZIP(), []int{5}
}

func (x *GetItemsResponse) GetItems() []*models.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type PutItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Item          *models.Item           `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutItemRequest) Reset() {
	*x = PutItemRequest{}
	mi := &file_item_service_grpc_item_grpc_item_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutItemRequest) ProtoMessage() {}

func (x *PutItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_service_grpc_item_grpc_item_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutItemRequest.ProtoReflect.Descriptor instead.
func (*PutItemRequest) Descriptor() ([]byte, []int) {
	return file_item_service_grpc_item_grpc_item_proto_rawDescGZIP(), []int{6}
}

func (x *PutItemRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PutItemRequest) GetItem() *models.Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type PutItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *models.Item           `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutItemResponse) Reset() {
	*x = PutItemResponse{}
	mi := &file_item_service_grpc_item_grpc_item_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutItemResponse) ProtoMessage() {}

func (x *PutItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_service_grpc_item_grpc_item_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutItemResponse.ProtoReflect.Descriptor instead.
func (*PutItemResponse) Descriptor() ([]byte, []int) {
	return file_item_service_grpc_item_grpc_item_proto_rawDescGZIP(), []int{7}
}

func (x *PutItemResponse) GetItem() *models.Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *PutItemResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PutItemResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DeleteItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemRequest) Reset() {
	*x = DeleteItemRequest{}
	mi := &file_item_service_grpc_item_grpc_item_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemRequest) ProtoMessage() {}

func (x *DeleteItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_item_service_grpc_item_grpc_item_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return file_item_service_grpc_item_grpc_item_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteItemRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemResponse) Reset() {
	*x = DeleteItemResponse{}
	mi := &file_item_service_grpc_item_grpc_item_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemResponse) ProtoMessage() {}

func (x *DeleteItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_item_service_grpc_item_grpc_item_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteItemResponse) Descriptor() ([]byte, []int) {
	return file_item_service_grpc_item_grpc_item_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_item_service_grpc_item_grpc_item_proto protoreflect.FileDescriptor

const file_item_service_grpc_item_grpc_item_proto_rawDesc = "" +
	"\n" +
	"&item-service/grpc/item-grpc/item.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgrpc/models/structures.proto\x1a\x17validate/validate.proto\"5\n" +
	"\x11CreateItemRequest\x12 \n" +
	"\x04item\x18\x01 \x01(\v2\f.models.ItemR\x04item\"q\n" +
	"\x12CreateItemResponse\x12!\n" +
	"\amessage\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x05R\amessage\x128\n" +
	"\tcreatedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\")\n" +
	"\x0eGetItemRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\rB\a\xfaB\x04*\x02 \x00R\x02id\"3\n" +
	"\x0fGetItemResponse\x12 \n" +
	"\x04item\x18\x01 \x01(\v2\f.models.ItemR\x04item\"?\n" +
	"\x0fGetItemsRequest\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\"6\n" +
	"\x10GetItemsResponse\x12\"\n" +
	"\x05items\x18\x01 \x03(\v2\f.models.ItemR\x05items\"K\n" +
	"\x0ePutItemRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\rB\a\xfaB\x04*\x02 \x00R\x02id\x12 \n" +
	"\x04item\x18\x02 \x01(\v2\f.models.ItemR\x04item\"\xa7\x01\n" +
	"\x0fPutItemResponse\x12 \n" +
	"\x04item\x18\x01 \x01(\v2\f.models.ItemR\x04item\x128\n" +
	"\tcreatedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\",\n" +
	"\x11DeleteItemRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\rB\a\xfaB\x04*\x02 \x00R\x02id\".\n" +
	"\x12DeleteItemResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xaf\x03\n" +
	"\vItemService\x12W\n" +
	"\n" +
	"CreateItem\x12\x18.proto.CreateItemRequest\x1a\x19.proto.CreateItemResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x04item\"\x06/items\x12M\n" +
	"\aGetItem\x12\x15.proto.GetItemRequest\x1a\x16.proto.GetItemResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/items/{id}\x12K\n" +
	"\bGetItems\x12\x16.proto.GetItemsRequest\x1a\x17.proto.GetItemsResponse\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/items\x12S\n" +
	"\aPutItem\x12\x15.proto.PutItemRequest\x1a\x16.proto.PutItemResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x04item\x1a\v/items/{id}\x12V\n" +
	"\n" +
	"DeleteItem\x12\x18.proto.DeleteItemRequest\x1a\x19.proto.DeleteItemResponse\"\x13\x82\xd3\xe4\x93\x02\r*\v/items/{id}B\x16Z\x14grpc/item-grpc;protob\x06proto3"

var (
	file_item_service_grpc_item_grpc_item_proto_rawDescOnce sync.Once
	file_item_service_grpc_item_grpc_item_proto_rawDescData []byte
)

func file_item_service_grpc_item_grpc_item_proto_rawDescGZIP() []byte {
	file_item_service_grpc_item_grpc_item_proto_rawDescOnce.Do(func() {
		file_item_service_grpc_item_grpc_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_item_service_grpc_item_grpc_item_proto_rawDesc), len(file_item_service_grpc_item_grpc_item_proto_rawDesc)))
	})
	return file_item_service_grpc_item_grpc_item_proto_rawDescData
}

var file_item_service_grpc_item_grpc_item_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_item_service_grpc_item_grpc_item_proto_goTypes = []any{
	(*CreateItemRequest)(nil),     // 0: proto.CreateItemRequest
	(*CreateItemResponse)(nil),    // 1: proto.CreateItemResponse
	(*GetItemRequest)(nil),        // 2: proto.GetItemRequest
	(*GetItemResponse)(nil),       // 3: proto.GetItemResponse
	(*GetItemsRequest)(nil),       // 4: proto.GetItemsRequest
	(*GetItemsResponse)(nil),      // 5: proto.GetItemsResponse
	(*PutItemRequest)(nil),        // 6: proto.PutItemRequest
	(*PutItemResponse)(nil),       // 7: proto.PutItemResponse
	(*DeleteItemRequest)(nil),     // 8: proto.DeleteItemRequest
	(*DeleteItemResponse)(nil),    // 9: proto.DeleteItemResponse
	(*models.Item)(nil),           // 10: models.Item
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 12: google.protobuf.Empty
}
var file_item_service_grpc_item_grpc_item_proto_depIdxs = []int32{
	10, // 0: proto.CreateItemRequest.item:type_name -> models.Item
	11, // 1: proto.CreateItemResponse.createdAt:type_name -> google.protobuf.Timestamp
	10, // 2: proto.GetItemResponse.item:type_name -> models.Item
	12, // 3: proto.GetItemsRequest.empty:type_name -> google.protobuf.Empty
	10, // 4: proto.GetItemsResponse.items:type_name -> models.Item
	10, // 5: proto.PutItemRequest.item:type_name -> models.Item
	10, // 6: proto.PutItemResponse.item:type_name -> models.Item
	11, // 7: proto.PutItemResponse.createdAt:type_name -> google.protobuf.Timestamp
	11, // 8: proto.PutItemResponse.updatedAt:type_name -> google.protobuf.Timestamp
	0,  // 9: proto.ItemService.CreateItem:input_type -> proto.CreateItemRequest
	2,  // 10: proto.ItemService.GetItem:input_type -> proto.GetItemRequest
	4,  // 11: proto.ItemService.GetItems:input_type -> proto.GetItemsRequest
	6,  // 12: proto.ItemService.PutItem:input_type -> proto.PutItemRequest
	8,  // 13: proto.ItemService.DeleteItem:input_type -> proto.DeleteItemRequest
	1,  // 14: proto.ItemService.CreateItem:output_type -> proto.CreateItemResponse
	3,  // 15: proto.ItemService.GetItem:output_type -> proto.GetItemResponse
	5,  // 16: proto.ItemService.GetItems:output_type -> proto.GetItemsResponse
	7,  // 17: proto.ItemService.PutItem:output_type -> proto.PutItemResponse
	9,  // 18: proto.ItemService.DeleteItem:output_type -> proto.DeleteItemResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_item_service_grpc_item_grpc_item_proto_init() }
func file_item_service_grpc_item_grpc_item_proto_init() {
	if File_item_service_grpc_item_grpc_item_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_item_service_grpc_item_grpc_item_proto_rawDesc), len(file_item_service_grpc_item_grpc_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_item_service_grpc_item_grpc_item_proto_goTypes,
		DependencyIndexes: file_item_service_grpc_item_grpc_item_proto_depIdxs,
		MessageInfos:      file_item_service_grpc_item_grpc_item_proto_msgTypes,
	}.Build()
	File_item_service_grpc_item_grpc_item_proto = out.File
	file_item_service_grpc_item_grpc_item_proto_goTypes = nil
	file_item_service_grpc_item_grpc_item_proto_depIdxs = nil
}
