// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: proto/lead-grpc/g-lead-product.proto

package proto

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	models "github.com/fiveret/api-gateway/grpc/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddProductsToLeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductIds    []uint32               `protobuf:"varint,2,rep,packed,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductsToLeadRequest) Reset() {
	*x = AddProductsToLeadRequest{}
	mi := &file_proto_lead_grpc_g_lead_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductsToLeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductsToLeadRequest) ProtoMessage() {}

func (x *AddProductsToLeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lead_grpc_g_lead_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductsToLeadRequest.ProtoReflect.Descriptor instead.
func (*AddProductsToLeadRequest) Descriptor() ([]byte, []int) {
	return file_proto_lead_grpc_g_lead_product_proto_rawDescGZIP(), []int{0}
}

func (x *AddProductsToLeadRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddProductsToLeadRequest) GetProductIds() []uint32 {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

type AddProductsToLeadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductsToLeadResponse) Reset() {
	*x = AddProductsToLeadResponse{}
	mi := &file_proto_lead_grpc_g_lead_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductsToLeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductsToLeadResponse) ProtoMessage() {}

func (x *AddProductsToLeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lead_grpc_g_lead_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductsToLeadResponse.ProtoReflect.Descriptor instead.
func (*AddProductsToLeadResponse) Descriptor() ([]byte, []int) {
	return file_proto_lead_grpc_g_lead_product_proto_rawDescGZIP(), []int{1}
}

func (x *AddProductsToLeadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteLeadProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     uint32                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLeadProductRequest) Reset() {
	*x = DeleteLeadProductRequest{}
	mi := &file_proto_lead_grpc_g_lead_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLeadProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLeadProductRequest) ProtoMessage() {}

func (x *DeleteLeadProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lead_grpc_g_lead_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLeadProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteLeadProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_lead_grpc_g_lead_product_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteLeadProductRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteLeadProductRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type DeleteLeadProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLeadProductResponse) Reset() {
	*x = DeleteLeadProductResponse{}
	mi := &file_proto_lead_grpc_g_lead_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLeadProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLeadProductResponse) ProtoMessage() {}

func (x *DeleteLeadProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lead_grpc_g_lead_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLeadProductResponse.ProtoReflect.Descriptor instead.
func (*DeleteLeadProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_lead_grpc_g_lead_product_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteLeadProductResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteLeadProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLeadProductsRequest) Reset() {
	*x = DeleteLeadProductsRequest{}
	mi := &file_proto_lead_grpc_g_lead_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLeadProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLeadProductsRequest) ProtoMessage() {}

func (x *DeleteLeadProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lead_grpc_g_lead_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLeadProductsRequest.ProtoReflect.Descriptor instead.
func (*DeleteLeadProductsRequest) Descriptor() ([]byte, []int) {
	return file_proto_lead_grpc_g_lead_product_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteLeadProductsRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteLeadProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLeadProductsResponse) Reset() {
	*x = DeleteLeadProductsResponse{}
	mi := &file_proto_lead_grpc_g_lead_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLeadProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLeadProductsResponse) ProtoMessage() {}

func (x *DeleteLeadProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lead_grpc_g_lead_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLeadProductsResponse.ProtoReflect.Descriptor instead.
func (*DeleteLeadProductsResponse) Descriptor() ([]byte, []int) {
	return file_proto_lead_grpc_g_lead_product_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteLeadProductsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetLeadProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     uint32                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeadProductsRequest) Reset() {
	*x = GetLeadProductsRequest{}
	mi := &file_proto_lead_grpc_g_lead_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeadProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeadProductsRequest) ProtoMessage() {}

func (x *GetLeadProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lead_grpc_g_lead_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeadProductsRequest.ProtoReflect.Descriptor instead.
func (*GetLeadProductsRequest) Descriptor() ([]byte, []int) {
	return file_proto_lead_grpc_g_lead_product_proto_rawDescGZIP(), []int{6}
}

func (x *GetLeadProductsRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetLeadProductsRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetLeadProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*models.ItemResponse `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeadProductsResponse) Reset() {
	*x = GetLeadProductsResponse{}
	mi := &file_proto_lead_grpc_g_lead_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeadProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeadProductsResponse) ProtoMessage() {}

func (x *GetLeadProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lead_grpc_g_lead_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeadProductsResponse.ProtoReflect.Descriptor instead.
func (*GetLeadProductsResponse) Descriptor() ([]byte, []int) {
	return file_proto_lead_grpc_g_lead_product_proto_rawDescGZIP(), []int{7}
}

func (x *GetLeadProductsResponse) GetProducts() []*models.ItemResponse {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *GetLeadProductsResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetLeadProductsResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetLeadsProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeadsProductsRequest) Reset() {
	*x = GetLeadsProductsRequest{}
	mi := &file_proto_lead_grpc_g_lead_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeadsProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeadsProductsRequest) ProtoMessage() {}

func (x *GetLeadsProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lead_grpc_g_lead_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeadsProductsRequest.ProtoReflect.Descriptor instead.
func (*GetLeadsProductsRequest) Descriptor() ([]byte, []int) {
	return file_proto_lead_grpc_g_lead_product_proto_rawDescGZIP(), []int{8}
}

func (x *GetLeadsProductsRequest) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

type GetLeadsProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*models.ItemResponse `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeadsProductsResponse) Reset() {
	*x = GetLeadsProductsResponse{}
	mi := &file_proto_lead_grpc_g_lead_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeadsProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeadsProductsResponse) ProtoMessage() {}

func (x *GetLeadsProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lead_grpc_g_lead_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeadsProductsResponse.ProtoReflect.Descriptor instead.
func (*GetLeadsProductsResponse) Descriptor() ([]byte, []int) {
	return file_proto_lead_grpc_g_lead_product_proto_rawDescGZIP(), []int{9}
}

func (x *GetLeadsProductsResponse) GetProducts() []*models.ItemResponse {
	if x != nil {
		return x.Products
	}
	return nil
}

type PutProductsLeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Product       *models.ItemRequest    `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutProductsLeadRequest) Reset() {
	*x = PutProductsLeadRequest{}
	mi := &file_proto_lead_grpc_g_lead_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutProductsLeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutProductsLeadRequest) ProtoMessage() {}

func (x *PutProductsLeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lead_grpc_g_lead_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutProductsLeadRequest.ProtoReflect.Descriptor instead.
func (*PutProductsLeadRequest) Descriptor() ([]byte, []int) {
	return file_proto_lead_grpc_g_lead_product_proto_rawDescGZIP(), []int{10}
}

func (x *PutProductsLeadRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PutProductsLeadRequest) GetProduct() *models.ItemRequest {
	if x != nil {
		return x.Product
	}
	return nil
}

type PutProductsLeadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutProductsLeadResponse) Reset() {
	*x = PutProductsLeadResponse{}
	mi := &file_proto_lead_grpc_g_lead_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutProductsLeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutProductsLeadResponse) ProtoMessage() {}

func (x *PutProductsLeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lead_grpc_g_lead_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutProductsLeadResponse.ProtoReflect.Descriptor instead.
func (*PutProductsLeadResponse) Descriptor() ([]byte, []int) {
	return file_proto_lead_grpc_g_lead_product_proto_rawDescGZIP(), []int{11}
}

func (x *PutProductsLeadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_lead_grpc_g_lead_product_proto protoreflect.FileDescriptor

const file_proto_lead_grpc_g_lead_product_proto_rawDesc = "" +
	"\n" +
	"$proto/lead-grpc/g-lead-product.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14models/gateway.proto\"T\n" +
	"\x18AddProductsToLeadRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\rB\a\xfaB\x04*\x02 \x00R\x02id\x12\x1f\n" +
	"\vproduct_ids\x18\x02 \x03(\rR\n" +
	"productIds\"5\n" +
	"\x19AddProductsToLeadResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"R\n" +
	"\x18DeleteLeadProductRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\rB\a\xfaB\x04*\x02 \x00R\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\rR\tproductId\"5\n" +
	"\x19DeleteLeadProductResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"4\n" +
	"\x19DeleteLeadProductsRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\rB\a\xfaB\x04*\x02 \x00R\x02id\"6\n" +
	"\x1aDeleteLeadProductsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"Y\n" +
	"\x16GetLeadProductsRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\rB\a\xfaB\x04*\x02 \x00R\x02id\x12&\n" +
	"\n" +
	"product_id\x18\x02 \x01(\rB\a\xfaB\x04*\x02 \x00R\tproductId\"\xbf\x01\n" +
	"\x17GetLeadProductsResponse\x120\n" +
	"\bproducts\x18\x01 \x03(\v2\x14.models.ItemResponseR\bproducts\x128\n" +
	"\tcreatedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"G\n" +
	"\x17GetLeadsProductsRequest\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\"L\n" +
	"\x18GetLeadsProductsResponse\x120\n" +
	"\bproducts\x18\x01 \x03(\v2\x14.models.ItemResponseR\bproducts\"`\n" +
	"\x16PutProductsLeadRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\rB\a\xfaB\x04*\x02 \x00R\x02id\x12-\n" +
	"\aproduct\x18\x02 \x01(\v2\x13.models.ItemRequestR\aproduct\"3\n" +
	"\x17PutProductsLeadResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x83\x06\n" +
	"\x12LeadProductService\x12z\n" +
	"\x11AddProductsToLead\x12\x1f.proto.AddProductsToLeadRequest\x1a .proto.AddProductsToLeadResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/leads/{id}/products\x12z\n" +
	"\x12DeleteLeadProducts\x12 .proto.DeleteLeadProductsRequest\x1a!.proto.DeleteLeadProductsResponse\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/v1/leads/{id}/products\x12\x84\x01\n" +
	"\x11DeleteLeadProduct\x12\x1f.proto.DeleteLeadProductRequest\x1a .proto.DeleteLeadProductResponse\",\x82\xd3\xe4\x93\x02&*$/v1/leads/{id}/products/{product_id}\x12\x82\x01\n" +
	"\x0fGetLeadProducts\x12\x1d.proto.GetLeadProductsRequest\x1a\x1e.proto.GetLeadProductsResponse\"0\x82\xd3\xe4\x93\x02*\x12(/v1/leads/{id}/lead-product/{product_id}\x12s\n" +
	"\x10GetLeadsProducts\x12\x1e.proto.GetLeadsProductsRequest\x1a\x1f.proto.GetLeadsProductsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/leads/lead-product\x12t\n" +
	"\x0fPutProductsLead\x12\x1d.proto.PutProductsLeadRequest\x1a\x1e.proto.PutProductsLeadResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\x1a\x17/v1/leads/{id}/productsB\x16Z\x14grpc/lead-grpc;protob\x06proto3"

var (
	file_proto_lead_grpc_g_lead_product_proto_rawDescOnce sync.Once
	file_proto_lead_grpc_g_lead_product_proto_rawDescData []byte
)

func file_proto_lead_grpc_g_lead_product_proto_rawDescGZIP() []byte {
	file_proto_lead_grpc_g_lead_product_proto_rawDescOnce.Do(func() {
		file_proto_lead_grpc_g_lead_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lead_grpc_g_lead_product_proto_rawDesc), len(file_proto_lead_grpc_g_lead_product_proto_rawDesc)))
	})
	return file_proto_lead_grpc_g_lead_product_proto_rawDescData
}

var file_proto_lead_grpc_g_lead_product_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_lead_grpc_g_lead_product_proto_goTypes = []any{
	(*AddProductsToLeadRequest)(nil),   // 0: proto.AddProductsToLeadRequest
	(*AddProductsToLeadResponse)(nil),  // 1: proto.AddProductsToLeadResponse
	(*DeleteLeadProductRequest)(nil),   // 2: proto.DeleteLeadProductRequest
	(*DeleteLeadProductResponse)(nil),  // 3: proto.DeleteLeadProductResponse
	(*DeleteLeadProductsRequest)(nil),  // 4: proto.DeleteLeadProductsRequest
	(*DeleteLeadProductsResponse)(nil), // 5: proto.DeleteLeadProductsResponse
	(*GetLeadProductsRequest)(nil),     // 6: proto.GetLeadProductsRequest
	(*GetLeadProductsResponse)(nil),    // 7: proto.GetLeadProductsResponse
	(*GetLeadsProductsRequest)(nil),    // 8: proto.GetLeadsProductsRequest
	(*GetLeadsProductsResponse)(nil),   // 9: proto.GetLeadsProductsResponse
	(*PutProductsLeadRequest)(nil),     // 10: proto.PutProductsLeadRequest
	(*PutProductsLeadResponse)(nil),    // 11: proto.PutProductsLeadResponse
	(*models.ItemResponse)(nil),        // 12: models.ItemResponse
	(*timestamppb.Timestamp)(nil),      // 13: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 14: google.protobuf.Empty
	(*models.ItemRequest)(nil),         // 15: models.ItemRequest
}
var file_proto_lead_grpc_g_lead_product_proto_depIdxs = []int32{
	12, // 0: proto.GetLeadProductsResponse.products:type_name -> models.ItemResponse
	13, // 1: proto.GetLeadProductsResponse.createdAt:type_name -> google.protobuf.Timestamp
	13, // 2: proto.GetLeadProductsResponse.updatedAt:type_name -> google.protobuf.Timestamp
	14, // 3: proto.GetLeadsProductsRequest.empty:type_name -> google.protobuf.Empty
	12, // 4: proto.GetLeadsProductsResponse.products:type_name -> models.ItemResponse
	15, // 5: proto.PutProductsLeadRequest.product:type_name -> models.ItemRequest
	0,  // 6: proto.LeadProductService.AddProductsToLead:input_type -> proto.AddProductsToLeadRequest
	4,  // 7: proto.LeadProductService.DeleteLeadProducts:input_type -> proto.DeleteLeadProductsRequest
	2,  // 8: proto.LeadProductService.DeleteLeadProduct:input_type -> proto.DeleteLeadProductRequest
	6,  // 9: proto.LeadProductService.GetLeadProducts:input_type -> proto.GetLeadProductsRequest
	8,  // 10: proto.LeadProductService.GetLeadsProducts:input_type -> proto.GetLeadsProductsRequest
	10, // 11: proto.LeadProductService.PutProductsLead:input_type -> proto.PutProductsLeadRequest
	1,  // 12: proto.LeadProductService.AddProductsToLead:output_type -> proto.AddProductsToLeadResponse
	5,  // 13: proto.LeadProductService.DeleteLeadProducts:output_type -> proto.DeleteLeadProductsResponse
	3,  // 14: proto.LeadProductService.DeleteLeadProduct:output_type -> proto.DeleteLeadProductResponse
	7,  // 15: proto.LeadProductService.GetLeadProducts:output_type -> proto.GetLeadProductsResponse
	9,  // 16: proto.LeadProductService.GetLeadsProducts:output_type -> proto.GetLeadsProductsResponse
	11, // 17: proto.LeadProductService.PutProductsLead:output_type -> proto.PutProductsLeadResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_lead_grpc_g_lead_product_proto_init() }
func file_proto_lead_grpc_g_lead_product_proto_init() {
	if File_proto_lead_grpc_g_lead_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lead_grpc_g_lead_product_proto_rawDesc), len(file_proto_lead_grpc_g_lead_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lead_grpc_g_lead_product_proto_goTypes,
		DependencyIndexes: file_proto_lead_grpc_g_lead_product_proto_depIdxs,
		MessageInfos:      file_proto_lead_grpc_g_lead_product_proto_msgTypes,
	}.Build()
	File_proto_lead_grpc_g_lead_product_proto = out.File
	file_proto_lead_grpc_g_lead_product_proto_goTypes = nil
	file_proto_lead_grpc_g_lead_product_proto_depIdxs = nil
}
