// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: api-gateway/grpc/lead-grpc/lead-product.proto

package proto

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	models "github.com/fiveret/api-gateway/grpc/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddProductsToLeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     []string               `protobuf:"bytes,2,rep,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductsToLeadRequest) Reset() {
	*x = AddProductsToLeadRequest{}
	mi := &file_api_gateway_grpc_lead_grpc_lead_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductsToLeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductsToLeadRequest) ProtoMessage() {}

func (x *AddProductsToLeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_grpc_lead_grpc_lead_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductsToLeadRequest.ProtoReflect.Descriptor instead.
func (*AddProductsToLeadRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_grpc_lead_grpc_lead_product_proto_rawDescGZIP(), []int{0}
}

func (x *AddProductsToLeadRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddProductsToLeadRequest) GetProductId() []string {
	if x != nil {
		return x.ProductId
	}
	return nil
}

type AddProductsToLeadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductsToLeadResponse) Reset() {
	*x = AddProductsToLeadResponse{}
	mi := &file_api_gateway_grpc_lead_grpc_lead_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductsToLeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductsToLeadResponse) ProtoMessage() {}

func (x *AddProductsToLeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_grpc_lead_grpc_lead_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductsToLeadResponse.ProtoReflect.Descriptor instead.
func (*AddProductsToLeadResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_grpc_lead_grpc_lead_product_proto_rawDescGZIP(), []int{1}
}

func (x *AddProductsToLeadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetLeadProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeadProductsRequest) Reset() {
	*x = GetLeadProductsRequest{}
	mi := &file_api_gateway_grpc_lead_grpc_lead_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeadProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeadProductsRequest) ProtoMessage() {}

func (x *GetLeadProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_grpc_lead_grpc_lead_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeadProductsRequest.ProtoReflect.Descriptor instead.
func (*GetLeadProductsRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_grpc_lead_grpc_lead_product_proto_rawDescGZIP(), []int{2}
}

func (x *GetLeadProductsRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetLeadProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *models.Product        `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	ProductId     uint32                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeadProductsResponse) Reset() {
	*x = GetLeadProductsResponse{}
	mi := &file_api_gateway_grpc_lead_grpc_lead_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeadProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeadProductsResponse) ProtoMessage() {}

func (x *GetLeadProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_grpc_lead_grpc_lead_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeadProductsResponse.ProtoReflect.Descriptor instead.
func (*GetLeadProductsResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_grpc_lead_grpc_lead_product_proto_rawDescGZIP(), []int{3}
}

func (x *GetLeadProductsResponse) GetProduct() *models.Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *GetLeadProductsResponse) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *GetLeadProductsResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetLeadProductsResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetLeadsProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeadsProductsRequest) Reset() {
	*x = GetLeadsProductsRequest{}
	mi := &file_api_gateway_grpc_lead_grpc_lead_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeadsProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeadsProductsRequest) ProtoMessage() {}

func (x *GetLeadsProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_grpc_lead_grpc_lead_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeadsProductsRequest.ProtoReflect.Descriptor instead.
func (*GetLeadsProductsRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_grpc_lead_grpc_lead_product_proto_rawDescGZIP(), []int{4}
}

func (x *GetLeadsProductsRequest) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

type GetLeadsProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*models.Product      `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeadsProductsResponse) Reset() {
	*x = GetLeadsProductsResponse{}
	mi := &file_api_gateway_grpc_lead_grpc_lead_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeadsProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeadsProductsResponse) ProtoMessage() {}

func (x *GetLeadsProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_grpc_lead_grpc_lead_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeadsProductsResponse.ProtoReflect.Descriptor instead.
func (*GetLeadsProductsResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_grpc_lead_grpc_lead_product_proto_rawDescGZIP(), []int{5}
}

func (x *GetLeadsProductsResponse) GetProducts() []*models.Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type PutProductsLeadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Product       *models.Product        `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutProductsLeadRequest) Reset() {
	*x = PutProductsLeadRequest{}
	mi := &file_api_gateway_grpc_lead_grpc_lead_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutProductsLeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutProductsLeadRequest) ProtoMessage() {}

func (x *PutProductsLeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_grpc_lead_grpc_lead_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutProductsLeadRequest.ProtoReflect.Descriptor instead.
func (*PutProductsLeadRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_grpc_lead_grpc_lead_product_proto_rawDescGZIP(), []int{6}
}

func (x *PutProductsLeadRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PutProductsLeadRequest) GetProduct() *models.Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type PutProductsLeadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutProductsLeadResponse) Reset() {
	*x = PutProductsLeadResponse{}
	mi := &file_api_gateway_grpc_lead_grpc_lead_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutProductsLeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutProductsLeadResponse) ProtoMessage() {}

func (x *PutProductsLeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_grpc_lead_grpc_lead_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutProductsLeadResponse.ProtoReflect.Descriptor instead.
func (*PutProductsLeadResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_grpc_lead_grpc_lead_product_proto_rawDescGZIP(), []int{7}
}

func (x *PutProductsLeadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteLeadProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLeadProductsRequest) Reset() {
	*x = DeleteLeadProductsRequest{}
	mi := &file_api_gateway_grpc_lead_grpc_lead_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLeadProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLeadProductsRequest) ProtoMessage() {}

func (x *DeleteLeadProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_grpc_lead_grpc_lead_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLeadProductsRequest.ProtoReflect.Descriptor instead.
func (*DeleteLeadProductsRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_grpc_lead_grpc_lead_product_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteLeadProductsRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteLeadProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLeadProductsResponse) Reset() {
	*x = DeleteLeadProductsResponse{}
	mi := &file_api_gateway_grpc_lead_grpc_lead_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLeadProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLeadProductsResponse) ProtoMessage() {}

func (x *DeleteLeadProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_grpc_lead_grpc_lead_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLeadProductsResponse.ProtoReflect.Descriptor instead.
func (*DeleteLeadProductsResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_grpc_lead_grpc_lead_product_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteLeadProductsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_gateway_grpc_lead_grpc_lead_product_proto protoreflect.FileDescriptor

const file_api_gateway_grpc_lead_grpc_lead_product_proto_rawDesc = "" +
	"\n" +
	"-api-gateway/grpc/lead-grpc/lead-product.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgrpc/models/structures.proto\x1a\x17validate/validate.proto\"R\n" +
	"\x18AddProductsToLeadRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\rB\a\xfaB\x04*\x02 \x00R\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x03(\tR\tproductId\"5\n" +
	"\x19AddProductsToLeadResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"1\n" +
	"\x16GetLeadProductsRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\rB\a\xfaB\x04*\x02 \x00R\x02id\"\xd7\x01\n" +
	"\x17GetLeadProductsResponse\x12)\n" +
	"\aproduct\x18\x01 \x01(\v2\x0f.models.ProductR\aproduct\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\rR\tproductId\x128\n" +
	"\tcreatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"G\n" +
	"\x17GetLeadsProductsRequest\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\"G\n" +
	"\x18GetLeadsProductsResponse\x12+\n" +
	"\bproducts\x18\x01 \x03(\v2\x0f.models.ProductR\bproducts\"\\\n" +
	"\x16PutProductsLeadRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\rB\a\xfaB\x04*\x02 \x00R\x02id\x12)\n" +
	"\aproduct\x18\x02 \x01(\v2\x0f.models.ProductR\aproduct\"3\n" +
	"\x17PutProductsLeadResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"4\n" +
	"\x19DeleteLeadProductsRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\rB\a\xfaB\x04*\x02 \x00R\x02id\"6\n" +
	"\x1aDeleteLeadProductsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xab\x04\n" +
	"\x12LeadProductService\x12i\n" +
	"\x11AddProductsToLead\x12\x1f.proto.AddProductsToLeadRequest\x1a .proto.AddProductsToLeadResponse\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/leads\x12e\n" +
	"\x0fGetLeadProducts\x12\x1d.proto.GetLeadProductsRequest\x1a\x1e.proto.GetLeadProductsResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/leads/{id}\x12c\n" +
	"\x10GetLeadsProducts\x12\x1e.proto.GetLeadsProductsRequest\x1a\x1f.proto.GetLeadsProductsResponse\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/leads\x12n\n" +
	"\x12DeleteLeadProducts\x12 .proto.DeleteLeadProductsRequest\x1a!.proto.DeleteLeadProductsResponse\"\x13\x82\xd3\xe4\x93\x02\r*\v/leads/{id}\x12n\n" +
	"\x0fPutProductsLead\x12\x1d.proto.PutProductsLeadRequest\x1a\x1e.proto.PutProductsLeadResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\aproduct\x1a\v/leads/{id}B\x16Z\x14grpc/lead-grpc;protob\x06proto3"

var (
	file_api_gateway_grpc_lead_grpc_lead_product_proto_rawDescOnce sync.Once
	file_api_gateway_grpc_lead_grpc_lead_product_proto_rawDescData []byte
)

func file_api_gateway_grpc_lead_grpc_lead_product_proto_rawDescGZIP() []byte {
	file_api_gateway_grpc_lead_grpc_lead_product_proto_rawDescOnce.Do(func() {
		file_api_gateway_grpc_lead_grpc_lead_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_grpc_lead_grpc_lead_product_proto_rawDesc), len(file_api_gateway_grpc_lead_grpc_lead_product_proto_rawDesc)))
	})
	return file_api_gateway_grpc_lead_grpc_lead_product_proto_rawDescData
}

var file_api_gateway_grpc_lead_grpc_lead_product_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_gateway_grpc_lead_grpc_lead_product_proto_goTypes = []any{
	(*AddProductsToLeadRequest)(nil),   // 0: proto.AddProductsToLeadRequest
	(*AddProductsToLeadResponse)(nil),  // 1: proto.AddProductsToLeadResponse
	(*GetLeadProductsRequest)(nil),     // 2: proto.GetLeadProductsRequest
	(*GetLeadProductsResponse)(nil),    // 3: proto.GetLeadProductsResponse
	(*GetLeadsProductsRequest)(nil),    // 4: proto.GetLeadsProductsRequest
	(*GetLeadsProductsResponse)(nil),   // 5: proto.GetLeadsProductsResponse
	(*PutProductsLeadRequest)(nil),     // 6: proto.PutProductsLeadRequest
	(*PutProductsLeadResponse)(nil),    // 7: proto.PutProductsLeadResponse
	(*DeleteLeadProductsRequest)(nil),  // 8: proto.DeleteLeadProductsRequest
	(*DeleteLeadProductsResponse)(nil), // 9: proto.DeleteLeadProductsResponse
	(*models.Product)(nil),             // 10: models.Product
	(*timestamppb.Timestamp)(nil),      // 11: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 12: google.protobuf.Empty
}
var file_api_gateway_grpc_lead_grpc_lead_product_proto_depIdxs = []int32{
	10, // 0: proto.GetLeadProductsResponse.product:type_name -> models.Product
	11, // 1: proto.GetLeadProductsResponse.createdAt:type_name -> google.protobuf.Timestamp
	11, // 2: proto.GetLeadProductsResponse.updatedAt:type_name -> google.protobuf.Timestamp
	12, // 3: proto.GetLeadsProductsRequest.empty:type_name -> google.protobuf.Empty
	10, // 4: proto.GetLeadsProductsResponse.products:type_name -> models.Product
	10, // 5: proto.PutProductsLeadRequest.product:type_name -> models.Product
	0,  // 6: proto.LeadProductService.AddProductsToLead:input_type -> proto.AddProductsToLeadRequest
	2,  // 7: proto.LeadProductService.GetLeadProducts:input_type -> proto.GetLeadProductsRequest
	4,  // 8: proto.LeadProductService.GetLeadsProducts:input_type -> proto.GetLeadsProductsRequest
	8,  // 9: proto.LeadProductService.DeleteLeadProducts:input_type -> proto.DeleteLeadProductsRequest
	6,  // 10: proto.LeadProductService.PutProductsLead:input_type -> proto.PutProductsLeadRequest
	1,  // 11: proto.LeadProductService.AddProductsToLead:output_type -> proto.AddProductsToLeadResponse
	3,  // 12: proto.LeadProductService.GetLeadProducts:output_type -> proto.GetLeadProductsResponse
	5,  // 13: proto.LeadProductService.GetLeadsProducts:output_type -> proto.GetLeadsProductsResponse
	9,  // 14: proto.LeadProductService.DeleteLeadProducts:output_type -> proto.DeleteLeadProductsResponse
	7,  // 15: proto.LeadProductService.PutProductsLead:output_type -> proto.PutProductsLeadResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_gateway_grpc_lead_grpc_lead_product_proto_init() }
func file_api_gateway_grpc_lead_grpc_lead_product_proto_init() {
	if File_api_gateway_grpc_lead_grpc_lead_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_grpc_lead_grpc_lead_product_proto_rawDesc), len(file_api_gateway_grpc_lead_grpc_lead_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_grpc_lead_grpc_lead_product_proto_goTypes,
		DependencyIndexes: file_api_gateway_grpc_lead_grpc_lead_product_proto_depIdxs,
		MessageInfos:      file_api_gateway_grpc_lead_grpc_lead_product_proto_msgTypes,
	}.Build()
	File_api_gateway_grpc_lead_grpc_lead_product_proto = out.File
	file_api_gateway_grpc_lead_grpc_lead_product_proto_goTypes = nil
	file_api_gateway_grpc_lead_grpc_lead_product_proto_depIdxs = nil
}
